 select shohin_bunrui , sum(hanbai_tanka) from shohin group by shohin_bunrui union all select '全商品' , sum(hanbai_tanka) from shohin;
select shohin_bunrui , sum(hanbai_tanka) from shohin group by rollup(shohin_bunrui);
select shohin_bunrui , torokubi , sum(hanbai_tanka) from shohin group by shohin_bunrui , torokubi order by shohin_bunrui;
select case when grouping(shohin_bunrui) = 1 then '合計' else shohin_bunrui end , sum(hanbai_tanka) from shohin g
roup by rollup(shohin_bunrui);
select * from books;
select name from books;
select name , release_year from books;
select distinct release_year from books;
select name as "書籍名" , total_page as "総ページ数" from books;
select * from books where release_year = 2020;
select * from books where name = '宇宙の歴史';
select * from books where name like '%マンガ%';
select * from authors where gender = '男性' limit 3;
select  * from books where release_year is not null;
select * from books where total_page between 300 and 400;
select * from books where release_year in (2004 , 2008 , 2018);
select book_id , price * 1.1 as tax_included_price from book_sales;
select * from books where total_page < 100;
select * from stores where holiday <> '月曜日';
select * from books where release_year >= 2000 and total_page <= 200;
select count(*) from authors where gender = '女性';
select sum(figure) as sum from book_sales;
select avg(total_page) from books;
select max(total_page) , min(total_page) from books;
select * from books order by release_year desc;
select release_year , count(*) as books_num from books group by release_year order by books_num desc;
